/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinGameIndexRouteImport } from './routes/joinGame/index'
import { Route as CreateGameIndexRouteImport } from './routes/createGame/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinGameIndexRoute = JoinGameIndexRouteImport.update({
  id: '/joinGame/',
  path: '/joinGame/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateGameIndexRoute = CreateGameIndexRouteImport.update({
  id: '/createGame/',
  path: '/createGame/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createGame/': typeof CreateGameIndexRoute
  '/joinGame/': typeof JoinGameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createGame': typeof CreateGameIndexRoute
  '/joinGame': typeof JoinGameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/createGame/': typeof CreateGameIndexRoute
  '/joinGame/': typeof JoinGameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/createGame/' | '/joinGame/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/createGame' | '/joinGame'
  id: '__root__' | '/' | '/createGame/' | '/joinGame/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateGameIndexRoute: typeof CreateGameIndexRoute
  JoinGameIndexRoute: typeof JoinGameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joinGame/': {
      id: '/joinGame/'
      path: '/joinGame'
      fullPath: '/joinGame/'
      preLoaderRoute: typeof JoinGameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createGame/': {
      id: '/createGame/'
      path: '/createGame'
      fullPath: '/createGame/'
      preLoaderRoute: typeof CreateGameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateGameIndexRoute: CreateGameIndexRoute,
  JoinGameIndexRoute: JoinGameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
